# Generated by Django 4.0.2 on 2022-02-14 08:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name', 'last_name', '-joined_at']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['first_name', 'last_name', '-joined_at']},
        ),
        migrations.CreateModel(
            name='QuizSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, db_index=True, default=uuid.uuid4, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('dificulty_level', models.CharField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')], default=0, max_length=2)),
                ('author_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizsets', to='classroom.teacher')),
            ],
            options={
                'ordering': ['-created_at', 'dificulty_level'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qustion_value', models.TextField()),
                ('point', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(15, 'Hya hya, 1ta mcq tei 100 marks diye dao,Ajob Public')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quizset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qustions', to='classroom.quizset')),
            ],
            options={
                'ordering': ['point'],
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_value', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('qustion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='classroom.question')),
            ],
        ),
    ]
