# Generated by Django 4.0.2 on 2022-02-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_student_options_alter_teacher_options_quizset_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
    ]
