# Generated by Django 4.0.2 on 2022-02-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_alter_quizset_difficulty_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qustion_value',
            new_name='question_value',
        ),
    ]
