# Generated by Django 4.0.2 on 2022-02-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_rename_qustion_value_question_question_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_value',
            field=models.CharField(blank=True, default='None Of The Above', max_length=500),
        ),
    ]
