# Generated by Django 4.0.2 on 2022-02-14 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_alter_option_option_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=uuid.uuid4, max_length=300)),
                ('start_date', models.DateField(blank=True, default=datetime.date(2022, 2, 15))),
                ('start_time', models.TimeField(blank=True, default=datetime.time(20, 21, 50, 791209))),
                ('exam_duration', models.DurationField(blank=True, default=datetime.timedelta(seconds=3600))),
                ('quizset', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroom.quizset')),
            ],
        ),
    ]
