# Generated by Django 4.0.2 on 2022-02-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_quizevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizEvent',
        ),
    ]
