# Generated by Django 4.0.2 on 2022-02-14 15:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_delete_quizevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, default=uuid.uuid4, max_length=300)),
                ('start_date', models.DateField(blank=True, db_index=True, default=datetime.date(2022, 2, 15))),
                ('start_time', models.TimeField(blank=True, db_index=True, default=datetime.time(20, 35, 9, 401440))),
                ('exam_duration', models.DurationField(blank=True, default=datetime.timedelta(seconds=3600))),
                ('quizset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_event', to='classroom.quizset')),
            ],
            options={
                'ordering': ['start_date', 'start_time', '-exam_duration', 'title'],
            },
        ),
    ]
