# Generated by Django 4.0.2 on 2022-02-14 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_quizevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizevent',
            name='start_time',
            field=models.TimeField(blank=True, db_index=True, default=datetime.time(20, 46, 29, 854530)),
        ),
    ]
