# Generated by Django 4.0.2 on 2022-02-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_alter_quizevent_start_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizEvent',
        ),
    ]
