# Generated by Django 4.0.2 on 2022-02-14 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_quizevent_quizset_quiz_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizevent',
            name='start_time',
            field=models.TimeField(blank=True, db_index=True, default=datetime.time(20, 49, 30, 735539)),
        ),
    ]
