# Generated by Django 4.0.2 on 2022-02-14 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_alter_quizevent_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizevent',
            name='start_time',
            field=models.TimeField(blank=True, db_index=True, default=datetime.time(20, 53, 24, 551051)),
        ),
    ]
