# Generated by Django 4.0.2 on 2022-02-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_alter_quizevent_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizset',
            name='quiz_event',
        ),
        migrations.DeleteModel(
            name='QuizEvent',
        ),
    ]
