# Generated by Django 4.0.2 on 2022-02-14 15:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_remove_quizset_quiz_event_delete_quizevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, default=uuid.uuid4, max_length=300)),
                ('start_date', models.DateField(blank=True, db_index=True, default=datetime.date(2022, 2, 15))),
                ('start_time', models.TimeField(blank=True, db_index=True, default=datetime.time(21, 22, 6, 825419))),
                ('exam_duration', models.DurationField(blank=True, default=datetime.timedelta(seconds=3600))),
            ],
            options={
                'ordering': ['start_date', 'start_time', '-exam_duration', 'title'],
            },
        ),
        migrations.AddField(
            model_name='quizset',
            name='quiz_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizsets', to='classroom.quizevent'),
        ),
    ]
