# Generated by Django 4.0.2 on 2022-02-14 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0017_quizevent_quizset_quiz_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizevent',
            name='start_time',
            field=models.TimeField(blank=True, db_index=True, default=datetime.time(21, 31, 17, 791713)),
        ),
        migrations.RemoveField(
            model_name='quizset',
            name='quiz_event',
        ),
        migrations.AddField(
            model_name='quizset',
            name='quiz_event',
            field=models.ManyToManyField(blank=True, null=True, related_name='quizsets', to='classroom.QuizEvent'),
        ),
    ]
