# Generated by Django 4.0.2 on 2022-02-14 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0018_alter_quizevent_start_time_remove_quizset_quiz_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizevent',
            name='start_time',
            field=models.TimeField(blank=True, db_index=True, default=datetime.time(21, 32, 24, 156876)),
        ),
        migrations.AlterField(
            model_name='quizset',
            name='quiz_event',
            field=models.ManyToManyField(blank=True, related_name='quizsets', to='classroom.QuizEvent'),
        ),
    ]
