# Generated by Django 4.0.2 on 2022-02-14 19:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0021_quizevent_all_qsets_alter_quizevent_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='belongs_to_quiz_set',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='qus_options', to='classroom.quizset'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizevent',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date(2022, 2, 16)),
        ),
        migrations.AlterField(
            model_name='quizevent',
            name='start_time',
            field=models.TimeField(blank=True, db_index=True, default=datetime.time(0, 33, 15, 939993)),
        ),
    ]
