# Generated by Django 4.0.2 on 2022-02-14 19:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0025_remove_option_belongs_to_quiz_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizevent',
            name='start_time',
            field=models.TimeField(blank=True, db_index=True, default=datetime.time(0, 41, 9, 982938)),
        ),
        migrations.AlterField(
            model_name='quizset',
            name='quiz_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizsets', to='classroom.quizevent'),
        ),
    ]
