# Generated by Django 4.0.2 on 2022-02-14 19:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0026_alter_quizevent_start_time_alter_quizset_quiz_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizevent',
            name='host_classroom',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_quizes', to='classroom.classroom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizevent',
            name='start_time',
            field=models.TimeField(blank=True, db_index=True, default=datetime.time(1, 10, 42, 27726)),
        ),
    ]
