# Generated by Django 4.0.2 on 2022-02-15 06:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0027_quizevent_host_classroom_alter_quizevent_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizevent',
            name='start_time',
            field=models.TimeField(blank=True, db_index=True, default=datetime.time(12, 16, 45, 509240)),
        ),
        migrations.CreateModel(
            name='AnswerSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('quizevent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_sets', to='classroom.quizevent')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('answer_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='classroom.answerset')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='classroom.student')),
            ],
        ),
    ]
