# Generated by Django 4.0.2 on 2022-02-15 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0028_alter_quizevent_start_time_answerset_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerset',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='quizevent',
            name='start_time',
            field=models.TimeField(blank=True, db_index=True, default=datetime.time(12, 27, 17, 280189)),
        ),
    ]
