# Generated by Django 4.0.2 on 2022-02-15 06:59

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0029_alter_answerset_options_alter_quizevent_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerset',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quizevent',
            name='start_time',
            field=models.TimeField(blank=True, db_index=True, default=datetime.time(12, 29, 36, 277308)),
        ),
    ]
