# Generated by Django 4.0.2 on 2022-02-16 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0039_alter_quizevent_start_time_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizevent',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date(2022, 2, 17)),
        ),
        migrations.AlterField(
            model_name='quizevent',
            name='start_time',
            field=models.TimeField(blank=True, db_index=True, default=datetime.time(22, 18, 12, 135791)),
        ),
    ]
