# Generated by Django 4.0.2 on 2022-02-16 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0041_alter_question_quizset_alter_quizevent_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizevent',
            name='start_time',
            field=models.TimeField(blank=True, db_index=True, default=datetime.time(22, 26, 28, 433920)),
        ),
    ]
