# Generated by Django 4.0.2 on 2022-02-16 17:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0043_alter_quizevent_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quizset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qustions', to='classroom.quizset'),
        ),
        migrations.AlterField(
            model_name='quizevent',
            name='start_time',
            field=models.TimeField(blank=True, db_index=True, default=datetime.time(22, 34, 54, 279596)),
        ),
    ]
